- id: doi:10.1534/g3.120.401516
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/g3journal/10/9/10.1534_g3.120.401516/7/m_3417f3.jpeg
  date: 2020-9-1
  tags:
    - Basidiobolus SM Genomics

- id: doi:10.1126/science.aba5256
  image: https://www.science.org/cms/10.1126/science.aba5256/asset/1559f60b-f99a-4a15-b040-b1c611e6652c/assets/graphic/368_aba5256_fa.jpeg

- id: doi:10.1094/MPMI-05-19-0131-R
  image: https://apsjournals.apsnet.org/cms/10.1094/MPMI-05-19-0131-R/asset/images/medium/mpmi-05-19-0131-r_f1.gif
